blank_issues_enabled: true
contact_links:
  - name: Documentation
    url: https://github.com/dav/IntelliJSpatialPlugin#readme
    about: Check the project README first.
  - name: Getting Help
    url: https://plugins.jetbrains.com/docs/intellij/getting-help.html
    about: General IntelliJ Platform plugin development help.
